### ISSUE TITLE
Can't get past root screen

### ISSUE THREAD

**Issue by LayerCZ** [SoulForeverInPeace/Boot-PC#2]
When I press grant su Acces and grant it it tells me "oops looks like we can't leave this page", can't get around it anyway

**Comment by LayerCZ** [comment]
I have now realized I can get past it normally with an older version, looks like your UI change messed it up

**Comment by SoulForeverInPeace** [comment]
weird. let me check.

[one old version atcully dont check su access(rather, will only let you in if you dont grant)]

**Comment by LayerCZ** [comment]
The version i was talking about is 1.2, i can get past that screen there but when i select a file then the app crashes so its still unusable

**Comment by SoulForeverInPeace** [comment]
can you post the crash report?

**Comment by LayerCZ** [comment]
[penis.txt](https://github.com/SoulForeverInPeace/Boot-PC/files/12136746/penis.txt)
sure, i could only get this out of it hope its enough

**Comment by SoulForeverInPeace** [comment]
About that error, it's due to filemanager. I am aware of this issue and am not exactly sure how to fix this at the moment.

  [ from what I read, not all file-manager returns the same thing. Thus the error] . I will solve the crash issue soon hopefully. For the time being use the, other filePicker(the ui suk tho)

unique taste in file name! Don't post again in public place.

**Comment by SoulForeverInPeace** [comment]
See if this crashes or not - [only crash issue]
https://github.com/SoulForeverInPeace/Boot-PC/releases/download/v1.4/fixes-app-release-23jul2023.apk

**Comment by LayerCZ** [comment]
Well this also crashes while using the default option which opens miexplorer (Chinese version) for me, but the other choice "floic" or smth works, but then when I hit start of course there is another error and it's not working and I can't scroll to see the full error, I do have the computer connected I tried switching to file transfer idk

**Comment by SoulForeverInPeace** [comment]
You don't need to pick any transfer type manually.

THAT info page is not scrollable since the few things you see are the only one's. This mainly helped me to resolve issue.

Can you give a me picture after you click "start"?

**Comment by LayerCZ** [comment]
Sure! Here you go
[Screenshot_2023-07-22-22-13-40-501_com.my.mdmd.jpg](https://github.com/SoulForeverInPeace/Boot-PC/assets/70105041/01c4696b-e262-4e6b-a6d5-b82b55edc128)

**Comment by SoulForeverInPeace** [comment]
You also don't need to be connected to pc for the app to work. 

Are you free for next 15min?

**Comment by LayerCZ** [comment]
Yeah I wasn't and yes I got plenty of time right now

**Comment by SoulForeverInPeace** [comment]
OKYY looks like you get one extra error message which I added in last few days

**Comment by SoulForeverInPeace** [comment]
I guess will have make it scrollable.

Do you use termux?

**Comment by LayerCZ** [comment]
Yes I do

**Comment by SoulForeverInPeace** [comment]
Kindly install file tree and run the following
(Give me a min)

**Comment by LayerCZ** [comment]
Do you maybe want to take this to discord or something because it's kinda annoying to communicate like this over GitHub yk

**Comment by SoulForeverInPeace** [comment]
Install tree `pkg install tree`
Now run -` tree  /config/usb_gadget/g1`

**Comment by SoulForeverInPeace** [comment]
Sure, give me your discord link

**Comment by LayerCZ** [comment]
@layercz is my discord, I have the output ready for you

**Comment by SoulForeverInPeace** [comment]
My discord user name peacefulsoul72929373
