### ISSUE TITLE
[disscuss] Color is missing for @color/ic_launcher_background"

### ISSUE THREAD

**Issue by SoulForeverInPeace** [SoulForeverInPeace/Boot-PC#8]
Sup @blessingmwiti

**Comment by blessingmwiti** [comment]
> Sup @blessingmwiti

Hey buddy, let me work on it

**Comment by SoulForeverInPeace** [comment]
wait. give me 15min. i looked into your code and found current code is 1commit behind (i forgot. ui changes)

**Comment by blessingmwiti** [comment]
oh, okay

**Comment by blessingmwiti** [comment]
did it resolve the color is missing issue?

**Comment by SoulForeverInPeace** [comment]
no. my above comment was for ui colors.

regarding this, i did added a color in colors.xml & changed the drwable to resolve errors. Though i succedeed, however failed to get the new icon you added.

**Comment by blessingmwiti** [comment]
I'll be requesting a merge in a few with the icon, using your recent updated repo

**Comment by SoulForeverInPeace** [comment]
Oky and also my apology. 

Only yesterday did I discovered force pushing causes issues. I will learn git properly Insha Allaah.

**Comment by blessingmwiti** [comment]
Inshallah
