### ISSUE TITLE
Error building

### ISSUE THREAD

**Issue by blessingmwiti** [SoulForeverInPeace/Boot-PC#9]
The following build output error is displayed
Android resource linking failed
com.my.mdmd.app-mergeDebugResources-39:/layout/activity_about.xml:12: error: '?style/textColorBootPc' is incompatible with attribute textColor (attr) reference|color.
error: failed linking file resources.

**Comment by blessingmwiti** [comment]
ayy @SoulForeverInPeace

**Comment by SoulForeverInPeace** [comment]
remove that and use this `#5C5C5C` color.

 [ i vaguely remember, i added custom style to be able to call from code probably, nvm it was not uses]

**Comment by blessingmwiti** [comment]
Okay, I tried adding color in the colors.xml, but it made things worse

**Comment by SoulForeverInPeace** [comment]
you can write the color directly here - layout/activity_about.xml:12: error: '?style/textColorBootPc' 

. or just remove the line error texetcolor line.

[also feel free to apply, change, fix according to your wish. as long as things dont go to worse, its highly welcome :) ]

**Comment by blessingmwiti** [comment]
Adding hex color directly solved the issue mate
